config/routes.rb
Rails.application.routes.draw do
  root 'breweries#index'

  get 'beerlist', to: 'beers#list'
  get 'brewerylist', to: 'breweries#list'
  get 'signin', to: 'sessions#new'
  get 'signup', to: 'users#new'
  post 'places', to: 'places#search'
  delete 'signout', to: 'sessions#destroy'

  resource :session, only: [:new, :create, :destroy]

  resources :beer_clubs
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :memberships, only: [:new, :create, :destroy]
  resources :places, only: [:index, :show]
  resources :ratings, only: [:index, :new, :create, :destroy]
  resources :styles
  resources :users do
    post 'toggle_ban_status', on: :member
  end
end

app/models/style.rb
class Style < ApplicationRecord
  include RatingAverage
  include RatingBest

  has_many :beers
  has_many :ratings, through: :beers

  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  before_action :ensure_that_admin, only: [:destroy]
  before_action :ensure_that_signed_in, except: [:index, :show]
  before_action :set_style, only: [:show, :edit, :update, :destroy]

  def index
    @styles = Style.all
  end

  def show
  end

  def new
    @style = Style.new
  end

  def edit
  end

  def create
    @style = Style.new(style_params)

    respond_to do |format|
      if @style.save
        format.html { redirect_to styles_url, notice: 'Style was successfully created.' }
        format.json { render :show, status: :created, location: @style }
      else
        format.html { render :new }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @style.update(style_params)
        format.html { redirect_to @style, notice: 'Style was successfully updated.' }
        format.json { render :show, status: :ok, location: @style }
      else
        format.html { render :edit }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @style.destroy
    respond_to do |format|
      format.html { redirect_to styles_url, notice: 'Style was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_style
    @style = Style.find(params[:id])
  end

  def style_params
    params.require(:style).permit(:name, :description)
  end
end

app/views/styles/_form.html.erb
<%= form_with(model: style, local: true) do |form| %>
  <% if @style.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(style.errors.count, "error") %> prohibited this style from being saved:</h2>

      <ul>
      <% style.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, {
      class: "form-control",
      placeholder: "Enter style name"
    } %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, {
      class: "form-control",
      rows: 5,
      placeholder: "Enter style description"
    } %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/styles/edit.html.erb
<h1>Editing Style</h1>

<%= render 'form', style: @style %>

<%= link_to 'Show', @style %> |
<%= link_to 'Back', styles_path %>

app/views/styles/index.html.erb
<h1>List of styles</h1>

<ul>
  <% @styles.each do |style| %>
    <li><%= link_to style.name, style %></li>
  <% end %>
</ul>
<br/>

<%= link_to 'New style', new_style_path if current_user %>

app/views/styles/new.html.erb
<h1>New Style</h1>

<%= render 'form', style: @style %>

<%= link_to 'Back', styles_path %>

app/views/styles/show.html.erb
<h2><%= @style.name %></h2>

<% if @style.description %>
  <p><%= @style.description %></p>
<% else %>
  <i>No description yet.</i>
<% end %>

<h3>beers</h3>

<li>
  <% if @style.beers.empty? %>
    <i>This style has no beers yet.</i>
  <% else %>
    <% @style.beers.each do |beer| %>
      <ul>
        <%= link_to beer.name, beer %> by <%= link_to beer.brewery.name, beer.brewery %>
      </ul>
    <% end %>
  <% end %>
</li>

<%= edit_and_destroy_buttons(@style) %>