config/routes.rb
Rails.application.routes.draw do
  root 'breweries#index'

  get 'beerlist', to: 'beers#list'
  get 'brewerylist', to: 'breweries#list'
  get 'signin', to: 'sessions#new'
  get 'signup', to: 'users#new'
  post 'places', to: 'places#search'
  delete 'signout', to: 'sessions#destroy'

  resource :session, only: [:new, :create, :destroy]

  resources :beer_clubs
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :memberships, only: [:new, :create, :destroy]
  resources :places, only: [:index, :show]
  resources :ratings, only: [:index, :new, :create, :destroy]
  resources :styles
  resources :users do
    post 'toggle_ban_status', on: :member
  end
end

app/models/brewery.rb
class Brewery < ApplicationRecord
  include RatingAverage
  include RatingBest

  has_many :beers, dependent: :destroy
  has_many :ratings, through: :beers

  validates :name, presence: true

  validates :year, numericality: {
    greater_than_or_equal_to: 1040,
    less_than_or_equal_to: proc { Date.current.year },
    only_integer: true
  }

  scope :active, -> { where active: true }
  scope :retired, -> { where active: [nil, false] }

  def current_year
    proc { Date.current.year }
  end

  def print_report
    puts name
    puts "established at year #{year}"
    puts "number of beers #{beers.size}"
  end

  def restart
    self.year = 2018
    puts "changed year to #{year}"
  end
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :ensure_that_admin, only: [:destroy]
  before_action :ensure_that_signed_in, except: [:index, :show, :list]
  before_action :set_brewery, only: [:show, :edit, :update, :destroy, :toggle_activity]

  # GET /breweries
  # GET /breweries.json
  def index
    return if request.format.html? && fragment_exist?('brewerylist')

    @breweries = Brewery.all
    @active_breweries, @retired_breweries = @breweries.partition(&:active)
  end

  # GET /breweries/1
  # GET /breweries/1.json
  def show
  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
  end

  # POST /breweries
  # POST /breweries.json
  def create
    expire_fragments

    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to @brewery, notice: 'Brewery was successfully created.' }
        format.json { render :show, status: :created, location: @brewery }
      else
        format.html { render :new }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1
  # PATCH/PUT /breweries/1.json
  def update
    expire_fragments

    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to @brewery, notice: 'Brewery was successfully updated.' }
        format.json { render :show, status: :ok, location: @brewery }
      else
        format.html { render :edit }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1
  # DELETE /breweries/1.json
  def destroy
    expire_fragments

    @brewery.destroy
    respond_to do |format|
      format.html { redirect_to breweries_url, notice: 'Brewery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_activity
    @brewery.update_attribute :active, !@brewery.active

    new_status = @brewery.active? ? "active" : "retired"

    redirect_to @brewery, notice: "This brewery is now #{new_status}."
  end

  def list
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_brewery
    @brewery = Brewery.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def brewery_params
    params.require(:brewery).permit(:name, :year, :active)
  end

  def expire_fragments
    expire_fragment("brewerylist")
  end
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_form.html.erb
<%= form_with(model: brewery, local: true) do |form| %>
  <% if brewery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
      <% brewery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name,
      class: "form-control",
      placeholder: "Enter name"
    %>
  </div>

  <div class="form-group">
    <%= form.label :year %>
    <%= form.number_field :year,
      class: "form-control",
      placeholder: "Enter year from 1040 to #{ brewery.current_year.call }"
    %>
  </div>

  <div class="form-check">
    <%= form.check_box :active, class: "form-check-input", checked: true %>
    <%= form.label :active %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/breweries/_list.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% breweries.each do |brewery| %>
      <tr>
        <td><%= link_to brewery.name, brewery %></td>
        <td><%= brewery.year %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/breweries/edit.html.erb
<h1>Editing Brewery</h1>

<%= render 'form', brewery: @brewery %>

<%= link_to 'Show', @brewery %> |
<%= link_to 'Back', breweries_path %>

app/views/breweries/index.html.erb
<h1>Breweries</h1>

<% cache "brewerylist", skip_digest: true do %>

  <h2>Active</h2>
  <p>Number of active breweries: <%= @active_breweries.size %></p>
  <%= render 'list', breweries: @active_breweries %>

  <h2>Retired</h2>
  <p>Number of retired breweries: <%= @retired_breweries.size %></p>
  <%= render 'list', breweries: @retired_breweries %>

<% end %>

<br>

<%= link_to 'New brewery', new_brewery_path if current_user %>

app/views/breweries/list.html.erb
<h2>Breweries</h2>

<table id="brewerytable" class="table table-hover">
  <thead>
    <tr>
      <th><a href="" id="name">Name</a></th>
      <th><a href="" id="year">Year</a></th>
      <th><a href="" id="beer_count">Beers</a></th>
      <th><a href="" id="active">Active</a></th>
    </tr>
  </thead>
</table>

app/views/breweries/new.html.erb
<h1>New Brewery</h1>

<%= render 'form', brewery: @brewery %>

<%= link_to 'Back', breweries_path %>

app/views/breweries/show.html.erb
<% cache @brewery do %>

  <h2>
    <%= @brewery.name %>
    <% if not @brewery.active %>
      <span class="badge badge-info">retired</span>
    <% end %>
  </h2>

  <p>
    <em>Established in <%= @brewery.year %></em>
  </p>

  <p>Number of beers: <%= @brewery.beers.size%></p>

  <p>
    <% @brewery.beers.each do |beer| %>
      <%= link_to beer.name, beer %>
    <% end %>
  </p>

  <p>
    <% if @brewery.average_rating %>
      Average rating: <%= round(@brewery.average_rating) %> <em>(Rated <%= pluralize(@brewery.ratings.size, 'time') %>)</em>
    <% else %>
      <em>This brewery has no ratings yet.</em>
    <% end %>
  </p>

<% end %>

<%= link_to "change activity", toggle_activity_brewery_path(@brewery.id), method: :post, class: "btn btn-primary" %><br/>

<%= edit_and_destroy_buttons(@brewery) %>