config/routes.rb
Rails.application.routes.draw do
  root 'breweries#index'

  get 'beerlist', to: 'beers#list'
  get 'brewerylist', to: 'breweries#list'
  get 'signin', to: 'sessions#new'
  get 'signup', to: 'users#new'
  post 'places', to: 'places#search'
  delete 'signout', to: 'sessions#destroy'

  resource :session, only: [:new, :create, :destroy]

  resources :beer_clubs
  resources :beers
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :memberships, only: [:new, :create, :destroy]
  resources :places, only: [:index, :show]
  resources :ratings, only: [:index, :new, :create, :destroy]
  resources :styles
  resources :users do
    post 'toggle_ban_status', on: :member
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ratebeer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to 'breweries', breweries_path, { class: "nav-link" } %>
          </li>      
          <li class="nav-item">
            <%= link_to 'beers', beers_path, { class: "nav-link" } %>
          </li>     
          <li class="nav-item">
            <%= link_to 'styles', styles_path, { class: "nav-link" } %>
          </li>   
          <li class="nav-item">
            <%= link_to 'ratings', ratings_path, { class: "nav-link" } %>
          </li>       
          <li class="nav-item">
            <%= link_to 'users', users_path, { class: "nav-link" } %>
          </li>  
          <li class="nav-item">
            <%= link_to 'clubs', beer_clubs_path, { class: "nav-link" } %>
          </li>   
          <li class="nav-item">
            <%= link_to 'places', places_path, { class: "nav-link" } %>
          </li> 
          <% if current_user %>
            <div class="dropdown">
              <button class="active nav-link btn-info dropdown-toggle" data-toggle="dropdown">
                <%= current_user.username %>
              </button>
              <div class="dropdown-menu">
                  <%= link_to 'my page', current_user, class: "dropdown-item" %>
                  <%= link_to 'rate a beer ', new_rating_path, class: "dropdown-item" %>  
                  <%= link_to 'join a club ', new_membership_path, class: "dropdown-item" %>
                  <%= link_to 'signout', signout_path, { class: "dropdown-item", method: :delete } %>
              </div>
            </div>
          <% else %>
            <li class="nav-item">
              <%= link_to 'signin', signin_path, { class: "nav-link" } %>
            </li>  
            <li class="nav-item">
              <%= link_to 'signup', signup_path, { class: "nav-link" } %>
            </li>
          <% end %>                            
        </ul>
      </div>
    </nav>

    <div class="container">
      <% if notice %>
        <div class="alert alert-primary" role="alert">
          <%= notice %>
        </div>
      <% end %>
      
      <div class="row">
        <div class="col-sm-8">
          <%= yield %>
        </div>
        <div class="col-sm-4">
          <%= image_tag "pint.jpg",
            width: 200,
            style: "padding-top: 30px"
          %>
        </div>
      </div>
    </div>
  </body>
</html>